---
title: 'CodeVid Studio'
author: "Kevin Buffardi"
date: "April 1, 2023"
output: ioslides_presentation
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
        
# CodeVid Studio: Coding Videos with Multimodal Instruction

by Kevin Buffardi


## Presentation

This is a brief summary of *CodeVid Studio: Coding Videos with Multimodal Instruction*, presented at the [Consortium for Computing Sciences in Colleges: Southwest](https://ccsc.org/southwestern/2023/) in Irvine, California and published in the *Journal for Computing Sciences in Colleges*.

This presentation page is available at [learnbyfailure.com/Codevid](https://learnbyfailure.com/CodeVid/) and its source is available on [GitHub](https://github.com/kbuffardi/CodeVid/).

## Issues in Teaching Coding Skills

Slides: summarize common presentation formats


## Multimedia Learning Principles
  
Show principles with good/bad examples

## Common Practices

Demonstrate common practices via Zoom or in-classroom

# CodeVid Studio

Demonstrate innovation

## Studio arrangement

Show how the studio is designed

## Implementation

Show the technical implementation, using chroma key

# Evaluation

Describe usability study

## Results

Comparison between CodeVid and talking-head-in-a-box

## Conclusions

* Advantages
* Building on a budget


# Full Paper

The full paper will be available soon.

<!--
[ACM Digital library](https://doi.org/10.1145/3502718.3524778)

To cite this paper, use the following reference in your bibliography:

> Kevin Buffardi and Richert Wang. 2022. Integrating Videos with Programming
Practice. In Proceedings of the 27th ACM Conference on Innovation and Technology in Computer Science Education Vol 1 (ITiCSE 2022), July 8–13, 2022, Dublin, Ireland. ACM, New York, NY, USA, 7 pages. https://doi.org/10.1145/3502718.3524778

Or import the following *BibTeX* reference:

```
@inproceedings{10.1145/3502718.3524778,
author = {Buffardi, Kevin and Wang, Richert}, title = {Integrating Videos with Programming Practice},year = {2022}, isbn = {9781450392013}, publisher = {Association for Computing Machinery}, address = {New York, NY, USA}, url = {https://doi.org/10.1145/3502718.3524778}, doi = {10.1145/3502718.3524778}, abstract = {There is an increasing variety of tools available to support students outside of the classroom as they learn how to program. However, broadening participation in computer science will also require these tools to reinforce inclusivity, diversity, and equity. To address these needs, two Hispanic-Serving Institutions, California State University, Chico (Chico State) and University of California, Santa Barbara (UCSB), are collaborating to produce video tutorials featuring students from historically marginalized communities. In these videos, students demonstrate uses of programming concepts in contexts that relate to their lives and interests. This experience report describes the development of the videos and associated programming practice problems. In a mixed-method observational study (n=188) of CS1 courses at the two universities, we investigated students' engagement with the videos and practice problems. Preliminary findings revealed that when the videos and practice problems were provided as separate links, students tended to watch the videos but not engage in the practice platform. Consequently, this paper also describes the development of Codewit.us, which integrates video lessons with an adaptive drill-and-practice programming interface. We found that when presented with the integrated interface, students were more likely to engage with practice in tandem with watching videos (instead of just watching videos without practice, as previously observed). The paper also describes thematic analysis of students' qualitative feedback on the videos and practice problems.}, booktitle = {Proceedings of the 27th ACM Conference on on Innovation and Technology in Computer Science Education Vol. 1}, pages = {241–247}, numpages = {7}, keywords = {computer science education, broadening participation, adaptive learning system, drill-and-practice, programming, cs1, coding, codewit.us, elearning, video}, location = {Dublin, Ireland},
series = {ITiCSE '22} }
```

-->
